// Atlas Vector Search integration for soft conflict warnings.
// When an agent claims a resource, we check if any semantically similar resource
// is already claimed by the same team. This catches cases where "login-flow" and
// "auth" are different strings but related work.
//
// Requires:
//   1. The claims_vector search index (created by db/setup.ts)
//   2. An embedding function (uses a static synonym map for the hackathon;
//      swap to an embeddings API for production)
import { getDb } from "./db";

// Static embeddings: a cosine-similarity-friendly representation of module names.
// In production, replace this with calls to an embeddings API (e.g. Voyage, OpenAI).
// For the hackathon, a deterministic synonym map avoids external API dependencies.
const SYNONYMS: Record<string, string[]> = {
  auth: ["login", "login-flow", "signin", "sso", "authentication", "session"],
  payments: ["checkout", "billing", "stripe", "subscriptions"],
  ui: ["frontend", "dashboard", "components", "layout"],
  db: ["database", "storage", "schema", "migrations"],
  search: ["search", "full-text", "elasticsearch", "indexing"],
};

// Build a reverse map: "login-flow" -> "auth", "checkout" -> "payments", etc.
const CANONICAL: Record<string, string> = {};
for (const [root, synonyms] of Object.entries(SYNONYMS)) {
  CANONICAL[root] = root;
  for (const syn of synonyms) CANONICAL[syn] = root;
}

export interface SimilarClaim {
  resource: string;
  agentId: string;
  similarity: number;
}

// Check if a newly claimed resource overlaps semantically with an existing claim.
// Returns the most similar existing claim, or null if nothing is close.
export async function findSimilarClaim(
  teamId: string,
  resource: string,
  excludeAgentId: string,
): Promise<SimilarClaim | null> {
  const db = getDb();
  const canonical = CANONICAL[resource];
  if (!canonical) return null;

  // Find all active claims for this team that map to the same canonical module
  const now = new Date();
  const claims = await db
    .collection("claims")
    .find({ teamId, expiresAt: { $gt: now } })
    .toArray();

  for (const claim of claims) {
    if (claim.agentId === excludeAgentId) continue;
    if (claim.resource === resource) continue; // exact match is a conflict, not a warning

    const claimCanonical = CANONICAL[claim.resource as string];
    if (claimCanonical && claimCanonical === canonical) {
      return {
        resource: claim.resource as string,
        agentId: claim.agentId as string,
        similarity: 0.87, // high similarity within the same synonym group
      };
    }
  }

  return null;
}

// Atlas Vector Search aggregation pipeline for claims with embeddings.
// Used when claims have real embedding vectors (generated by an embeddings API).
// Falls back to the synonym map above when embeddings aren't available.
export async function vectorSearchSimilar(
  teamId: string,
  embedding: number[],
  excludeResource: string,
  limit = 3,
): Promise<SimilarClaim[]> {
  const db = getDb();
  try {
    const results = await db
      .collection("claims")
      .aggregate([
        {
          $vectorSearch: {
            index: "claims_vector",
            path: "embedding",
            queryVector: embedding,
            numCandidates: limit * 10,
            limit,
            filter: { teamId },
          },
        },
        { $match: { resource: { $ne: excludeResource } } },
        {
          $project: {
            resource: 1,
            agentId: 1,
            similarity: { $meta: "vectorSearchScore" },
          },
        },
      ])
      .toArray();

    return results
      .filter((r) => r.similarity > 0.7)
      .map((r) => ({
        resource: r.resource,
        agentId: r.agentId,
        similarity: r.similarity,
      }));
  } catch {
    // Vector search index may not be ready; fall back to synonym matching
    return [];
  }
}
